//! Mirror of `packages/ai/src/models.generated.ts`.
//!
//! Auto-generated by `rust/scripts/generate_models.py`.
//! Do not edit manually — re-run the generator when model data changes.

use std::collections::HashMap;

use crate::types::Model;

use crate::providers::model_data::{
    amazon_bedrock_models, ant_ling_models, anthropic_models, azure_openai_responses_models,
    cerebras_models, cloudflare_ai_gateway_models, cloudflare_workers_ai_models, deepseek_models,
    fireworks_models, github_copilot_models, google_models, google_vertex_models, groq_models,
    huggingface_models, kimi_coding_models, minimax_cn_models, minimax_models, mistral_models,
    moonshotai_cn_models, moonshotai_models, nvidia_models, openai_codex_models, openai_models,
    opencode_go_models, opencode_models, openrouter_models, together_models,
    vercel_ai_gateway_models, xai_models, xiaomi_models, xiaomi_token_plan_ams_models,
    xiaomi_token_plan_cn_models, xiaomi_token_plan_sgp_models, zai_coding_cn_models, zai_models,
};

/// Build the provider → (model id → Model) registry.
pub fn models() -> HashMap<String, HashMap<String, Model>> {
    let mut map: HashMap<String, HashMap<String, Model>> = HashMap::new();

    // amazon-bedrock (97 models)
    map.insert("amazon-bedrock".into(), amazon_bedrock_models::models());

    // ant-ling (3 models)
    map.insert("ant-ling".into(), ant_ling_models::models());

    // anthropic (25 models)
    map.insert("anthropic".into(), anthropic_models::models());

    // azure-openai-responses (40 models)
    map.insert(
        "azure-openai-responses".into(),
        azure_openai_responses_models::models(),
    );

    // cerebras (2 models)
    map.insert("cerebras".into(), cerebras_models::models());

    // cloudflare-ai-gateway (35 models)
    map.insert(
        "cloudflare-ai-gateway".into(),
        cloudflare_ai_gateway_models::models(),
    );

    // cloudflare-workers-ai (13 models)
    map.insert(
        "cloudflare-workers-ai".into(),
        cloudflare_workers_ai_models::models(),
    );

    // deepseek (2 models)
    map.insert("deepseek".into(), deepseek_models::models());

    // fireworks (16 models)
    map.insert("fireworks".into(), fireworks_models::models());

    // github-copilot (22 models)
    map.insert("github-copilot".into(), github_copilot_models::models());

    // google (16 models)
    map.insert("google".into(), google_models::models());

    // google-vertex (10 models)
    map.insert("google-vertex".into(), google_vertex_models::models());

    // groq (7 models)
    map.insert("groq".into(), groq_models::models());

    // huggingface (47 models)
    map.insert("huggingface".into(), huggingface_models::models());

    // kimi-coding (2 models)
    map.insert("kimi-coding".into(), kimi_coding_models::models());

    // minimax (3 models)
    map.insert("minimax".into(), minimax_models::models());

    // minimax-cn (3 models)
    map.insert("minimax-cn".into(), minimax_cn_models::models());

    // mistral (30 models)
    map.insert("mistral".into(), mistral_models::models());

    // moonshotai (9 models)
    map.insert("moonshotai".into(), moonshotai_models::models());

    // moonshotai-cn (9 models)
    map.insert("moonshotai-cn".into(), moonshotai_cn_models::models());

    // nvidia (19 models)
    map.insert("nvidia".into(), nvidia_models::models());

    // openai (40 models)
    map.insert("openai".into(), openai_models::models());

    // openai-codex (4 models)
    map.insert("openai-codex".into(), openai_codex_models::models());

    // opencode (45 models)
    map.insert("opencode".into(), opencode_models::models());

    // opencode-go (13 models)
    map.insert("opencode-go".into(), opencode_go_models::models());

    // openrouter (255 models)
    map.insert("openrouter".into(), openrouter_models::models());

    // together (20 models)
    map.insert("together".into(), together_models::models());

    // vercel-ai-gateway (185 models)
    map.insert(
        "vercel-ai-gateway".into(),
        vercel_ai_gateway_models::models(),
    );

    // xai (7 models)
    map.insert("xai".into(), xai_models::models());

    // xiaomi (6 models)
    map.insert("xiaomi".into(), xiaomi_models::models());

    // xiaomi-token-plan-ams (5 models)
    map.insert(
        "xiaomi-token-plan-ams".into(),
        xiaomi_token_plan_ams_models::models(),
    );

    // xiaomi-token-plan-cn (5 models)
    map.insert(
        "xiaomi-token-plan-cn".into(),
        xiaomi_token_plan_cn_models::models(),
    );

    // xiaomi-token-plan-sgp (5 models)
    map.insert(
        "xiaomi-token-plan-sgp".into(),
        xiaomi_token_plan_sgp_models::models(),
    );

    // zai (6 models)
    map.insert("zai".into(), zai_models::models());

    // zai-coding-cn (6 models)
    map.insert("zai-coding-cn".into(), zai_coding_cn_models::models());

    map
}
